// Generated by eve. Do not edit by hand.

import * as module_0 from "../../../agent/agent.ts";
import * as module_1 from "../../../agent/hooks/trail.ts";
import * as module_2 from "../../../agent/sandbox.ts";
import * as module_3 from "../../../agent/tools/apply_repair.ts";
import * as module_4 from "../../../agent/tools/close_batch.ts";
import * as module_5 from "../../../agent/tools/escalate_to_desk.ts";
import * as module_6 from "../../../agent/tools/get_instruction.ts";
import * as module_7 from "../../../agent/tools/get_screening_status.ts";
import * as module_8 from "../../../agent/tools/list_repair_queue.ts";
import * as module_9 from "../../../agent/tools/lookup_reference_data.ts";
import * as module_10 from "../../../agent/tools/validate_instruction.ts";

export const moduleMap = Object.freeze({
  "nodes": Object.freeze({
      "__root__": Object.freeze({
              "modules": Object.freeze({
                  "agent.ts": module_0,
                  "hooks/trail.ts": module_1,
                  "sandbox.ts": module_2,
                  "tools/apply_repair.ts": module_3,
                  "tools/close_batch.ts": module_4,
                  "tools/escalate_to_desk.ts": module_5,
                  "tools/get_instruction.ts": module_6,
                  "tools/get_screening_status.ts": module_7,
                  "tools/list_repair_queue.ts": module_8,
                  "tools/lookup_reference_data.ts": module_9,
                  "tools/validate_instruction.ts": module_10
                })
            })
    })
});

export default moduleMap;
